Led Pulse: Pulse Class Reference
Pulse Class Reference
#include <Pulse.h>
Public Member Functions
Pulse (void)
Pulse (int p, int s=LOW, int i=false)
void breathe ()
Breath the led, pulse in and out using PWM.
void heartbeat ()
Flash the led like a heart-beat.
void flash ()
Flash the led continously.
void strobe ()
Strobe the led.
void blink ()
Blink the led.
void tick ()
Call this every loop to update the pulse led.
void stop ()
stop flashing!
void on (void)
Turn the led ON.
void off (void)
turn the led OFF
void timeout (uint32_t timeout, PulseMode_t modeOnTimeout=PULSE_INACTIVE)
Turn the led ON and then timeout.
Private Member Functions
void _setMode (PulseMode_t mode)
Private Attributes
uint32_t _lastInterval
uint32_t _timeout
PulseMode_t _mode
PulseMode_t _modeOnTimeout
uint8_t _count
uint16_t _heartbeat [4] = {20, 100, 20, 2000}
uint16_t _strobe [2] = {20, 1000}
uint16_t _flash [2] = {500, 500}
uint16_t _blink [2] = {20, 5000}
Detailed Description
Definition at line 23 of file Pulse.h.
Constructor & Destructor Documentation
Pulse() [1/2]
Pulse::Pulse (void)
Definition at line 4 of file Pulse.cpp.
 {}
Pulse() [2/2]
Pulse::Pulse (int p, int s = LOW, int i = false)
Definition at line 5 of file Pulse.cpp.
 : Output{p, s, i} {}
Member Function Documentation
_setMode()
void Pulse::_setMode (PulseMode_t mode) private
Definition at line 7 of file Pulse.cpp.
 {
     if (this->_mode != mode)
     {
         this->_mode = mode;
         this->_count = 0;
         this->_lastInterval = millis();
         if (this->_mode != PULSE_INACTIVE)
             this->set(true); // start the mode by turning the led on
     }
 }
References _count, _lastInterval, _mode, and PULSE_INACTIVE.
Referenced by blink(), breathe(), flash(), heartbeat(), strobe(), tick(), and timeout().
blink()
void Pulse::blink ()
Blink the led.
Definition at line 25 of file Pulse.cpp.
 { this->_setMode(PULSE_BLINK); }
References _setMode(), and PULSE_BLINK.
breathe()
void Pulse::breathe ()
Breath the led, pulse in and out using PWM.
Definition at line 21 of file Pulse.cpp.
 { this->_setMode(PULSE_BREATHE); }
References _setMode(), and PULSE_BREATHE.
flash()
void Pulse::flash ()
Flash the led continously.
Definition at line 24 of file Pulse.cpp.
 { this->_setMode(PULSE_FLASH); }
References _setMode(), and PULSE_FLASH.
heartbeat()
void Pulse::heartbeat ()
Flash the led like a heart-beat.
Definition at line 23 of file Pulse.cpp.
 { this->_setMode(PULSE_HEARTBEAT); }
References _setMode(), and PULSE_HEARTBEAT.
off()
void Pulse::off (void)
turn the led OFF
Definition at line 39 of file Pulse.cpp.
 {
     this->_mode = PULSE_INACTIVE;
     this->set(false);
 }
References _mode, and PULSE_INACTIVE.
Referenced by stop().
on()
void Pulse::on (void)
Turn the led ON.
Definition at line 33 of file Pulse.cpp.
 {
     this->_mode = PULSE_INACTIVE;
     this->set(true);
 }
References _mode, and PULSE_INACTIVE.
stop()
void Pulse::stop ()
stop flashing!
Definition at line 27 of file Pulse.cpp.
 {
     this->off();
     this->_mode = PULSE_INACTIVE;
 }
References _mode, off(), and PULSE_INACTIVE.
strobe()
void Pulse::strobe ()
Strobe the led.
Definition at line 22 of file Pulse.cpp.
 { this->_setMode(PULSE_STROBE); }
References _setMode(), and PULSE_STROBE.
tick()
void Pulse::tick ()
Call this every loop to update the pulse led.
Definition at line 52 of file Pulse.cpp.
 {
     switch (this->_mode)
     {
     case PulseMode_t::PULSE_BREATHE:
         break;
     case PulseMode_t::PULSE_HEARTBEAT:
         if (millis() - this->_lastInterval >= this->_heartbeat[this->_count])
         {
             this->_lastInterval = millis();
             if (++this->_count >= (sizeof(this->_heartbeat) / sizeof(this->_heartbeat[0])))
                 this->_count = 0;
             this->set(!(this->_count % 2)); // even is on
         }
         break;
     case PulseMode_t::PULSE_FLASH:
         if (millis() - this->_lastInterval >= this->_flash[this->_count])
         {
             this->_lastInterval = millis();
             if (++this->_count >= (sizeof(this->_flash) / sizeof(this->_flash[0])))
                 this->_count = 0;
             this->set(!(this->_count % 2)); // even is on
         }
         break;
     case PulseMode_t::PULSE_STROBE:
         if (millis() - this->_lastInterval >= this->_strobe[this->_count])
         {
             this->_lastInterval = millis();
             if (++this->_count >= (sizeof(this->_strobe) / sizeof(this->_strobe[0])))
                 this->_count = 0;
             this->set(!(this->_count % 2)); // even is on
         }
         break;
     case PulseMode_t::PULSE_BLINK:
         if (millis() - this->_lastInterval >= this->_blink[this->_count])
         {
             this->_lastInterval = millis();
             if (++this->_count >= (sizeof(this->_blink) / sizeof(this->_blink[0])))
                 this->_count = 0;
             this->set(!(this->_count % 2)); // even is on
         }
         break;
     case PulseMode_t::PULSE_TIMEOUT:
         if (millis() - this->_lastInterval >= this->_timeout)
         {
             this->set(false);
             this->_setMode(this->_modeOnTimeout);
         }
     case PulseMode_t::PULSE_INACTIVE:
         break;
     }
 }
References _blink, _count, _flash, _heartbeat, _lastInterval, _mode, _modeOnTimeout, _setMode(), _strobe, _timeout, PULSE_BLINK, PULSE_BREATHE, PULSE_FLASH, PULSE_HEARTBEAT, PULSE_INACTIVE, PULSE_STROBE, and PULSE_TIMEOUT.
timeout()
void Pulse::timeout (uint32_t timeout, PulseMode_t modeOnTimeout = PULSE_INACTIVE)
Turn the led ON and then timeout.
Parameters
timeout time to timeout (ms)
modeOnTimeout pulse mode to enable on timeout (Default PULSE_INACTIVE)
Definition at line 45 of file Pulse.cpp.
 {
     this->_timeout = timeout;
     this->_modeOnTimeout = modeOnTimeout;
     this->_setMode(PULSE_TIMEOUT);
 }
References _modeOnTimeout, _setMode(), _timeout, and PULSE_TIMEOUT.
Member Data Documentation
_blink
uint16_t Pulse::_blink[2] = {20, 5000} private
Definition at line 37 of file Pulse.h.
Referenced by tick().
_count
uint8_t Pulse::_count private
Definition at line 31 of file Pulse.h.
Referenced by _setMode(), and tick().
_flash
uint16_t Pulse::_flash[2] = {500, 500} private
Definition at line 36 of file Pulse.h.
Referenced by tick().
_heartbeat
uint16_t Pulse::_heartbeat[4] = {20, 100, 20, 2000} private
Definition at line 34 of file Pulse.h.
Referenced by tick().
_lastInterval
uint32_t Pulse::_lastInterval private
Definition at line 26 of file Pulse.h.
Referenced by _setMode(), and tick().
_mode
PulseMode_t Pulse::_mode private
Definition at line 29 of file Pulse.h.
Referenced by _setMode(), off(), on(), stop(), and tick().
_modeOnTimeout
PulseMode_t Pulse::_modeOnTimeout private
Definition at line 30 of file Pulse.h.
Referenced by tick(), and timeout().
_strobe
uint16_t Pulse::_strobe[2] = {20, 1000} private
Definition at line 35 of file Pulse.h.
Referenced by tick().
_timeout
uint32_t Pulse::_timeout private
Definition at line 27 of file Pulse.h.
Referenced by tick(), and timeout().
The documentation for this class was generated from the following files:
Pulse.h
Pulse.cpp